# Generated by Django 5.2.16 on 2026-07-30 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nombre del archivo'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='ruta remota'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size_kb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tamaño (KB)'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='tipo MIME'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nombre del archivo'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='ruta remota'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_size_kb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tamaño (KB)'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='tipo MIME'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt'])], verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='document_versions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt'])], verbose_name='archivo'),
        ),
    ]
