# Generated by Django 5.2.16 on 2026-07-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_name_document_file_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('view_reports', 'Puede consultar reportes')], 'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
    ]
