# Generated by Django 5.2.16 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="documents.document",
                verbose_name="documento revisado",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_document_updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="fecha de la versión revisada",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_file_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="archivo revisado",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_file_path",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="ruta del archivo revisado",
            ),
        ),
    ]
